services:
  - type: web
    name: cwl-manager
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    domains:
      - cwl-manager.onrender.com